### PR TITLE
Created property type analysis

### PR DESCRIPTION
**Pull request by mikevandiepen**
Added property type analysis.

- Wrote functionality for docblock supression analysis and default analysis
- Wrote tests

### CODE REVIEW

**Comment by mikevandiepen** [comment]
Hmm I've noticed not everything is right yet, I made it in a rush. I'll look into it later today!

**Comment by seferov** [comment]
Hi @mikevandiepen, thanks for PR!
I will check the build to see what's wrong.

**Comment by mikevandiepen** [comment]
Hi,

Since your codebase is rather "messy" and undocumented I have decided to take it up to myself to create a new and improved type analysis tool.

The tool is in beta testing now and I'm aiming to improve it even more.
The URL of the repo is: 
https://github.com/mikevandiepen/strictly 

This analysis library already contains the basic type analysis tools. The codebase is better documented more abstract and easier to maintain. It'd be nice if you take a look at the project. I'm aiming to make the console output more like "PhpInsight" which will be nicer =).

**Comment by seferov** [comment]
Hi @mikevandiepen,

Your code looks nice. Good luck with that!

**Pull request closed without merging**
